/**
 * Domain: **reasoning over the behaviour graph** (Phase 2.4 slice 2.7) — Layer 3, and nothing else.
 *
 *     graph (geometry)  ──▶  evaluate(rule, graph)  ──▶  candidate + WHY chain
 *
 * ### ⛔ Every clause of every answer comes from the graph
 *
 * This module reads nodes and edges and does no geometry of its own: no distance, no angle, no
 * duration it did not receive. That is the constraint the whole layering rests on — the moment a
 * rule computes its own proximity, there are two answers to "were they near each other" and an
 * investigator has no way to tell which one an incident used. Everything here is *selection* over
 * facts something else established.
 *
 * ### ⭐ The chain is the product, not a byline on it
 *
 * A candidate is assembled **from** its links. The summary is generated by joining them, the
 * confidence is measured off them, and the interval is their span. There is no path by which a
 * candidate can exist without a chain that produced it, which is what makes "every incident is
 * explainable" a structural property rather than a discipline somebody has to keep.
 *
 * ⚠️ **Non-matching links are kept.** A chain that only showed its successes would answer "why did
 * this fire" and never "why did this one not" — and the second question is the one asked when a rule
 * is being tuned, which is most of the time.
 *
 * Pure and deterministic: no clock, no I/O, no store.
 */
import type {
  BehaviourCandidate,
  BehaviourReasonLink,
  BehaviourRule,
  BehaviourStep,
} from '@vip/contracts';

/** The graph as the Behaviour API returns it. ⚠️ Structural, so the evaluator needs no zod at runtime. */
export interface GraphNode {
  id: string;
  kind: string;
  label: string;
  attributes: Record<string, unknown>;
}

export interface GraphEdge {
  id: string;
  kind: string;
  source: string;
  target: string;
  atSeconds: number;
  endSeconds?: number;
  seconds?: number;
  attributes: Record<string, unknown>;
  evidence: Record<string, unknown>;
}

export interface BehaviourGraphView {
  nodes: GraphNode[];
  edges: GraphEdge[];
  /**
   * Footage second of the run's first observation.
   *
   * ⛔ Every `atSeconds` on an edge is absolute. Rendering one directly produces
   * "at 1786221387.294 s", which is true and unreadable — the defect `TimelineEntry` documents and
   * which this layer reintroduced one level up before it was caught on the deployed stack.
   */
  originSeconds?: number;
  truncated?: {
    nodes: boolean;
    edges: boolean;
    relational: boolean;
    identitiesConsidered: number;
  };
}

/** Edge kinds whose `source` is the subject of the statement. */
const SUBJECT_IS_SOURCE = new Set([
  'visited',
  'crossed',
  'near',
  'followed',
  'approached',
  'receded',
  'member',
  'handedOver',
]);

/**
 * Edge kinds whose `source` is an **object** and whose `target` is the subject.
 *
 * ⚠️ `carried` points object → person because the statement is about the object (`behaviour_graph`
 * argues this). A rule step is written from the *subject's* side — "this person carried a bottle" —
 * so the two ends are swapped here rather than the graph being reshaped to suit rule authors.
 */
const SUBJECT_IS_TARGET = new Set(['carried', 'picked', 'dropped', 'wentMissing', 'returned']);

/** Steps that read a node attribute rather than an edge. */
const NODE_ATTRIBUTE_KINDS = new Set(['idle', 'linger']);

interface Match {
  atSeconds: number;
  endSeconds?: number;
  seconds?: number;
  edgeId?: string;
  nodeId?: string;
  evidence: Record<string, unknown>;
  detail: string;
  /** How many facts of this kind were examined — the honest denominator behind an absence. */
  considered: number;
}

/**
 * Every candidate one rule produces over one graph.
 *
 * ⚠️ Identities are evaluated independently and in a stable order, so two runs over one analysis
 * produce the same document — a report used for investigation must be reproducible.
 */
export function evaluateBehaviourRule(
  rule: BehaviourRule,
  graph: BehaviourGraphView,
): BehaviourCandidate[] {
  if (!rule.enabled) return [];

  const nodes = new Map(graph.nodes.map((n) => [n.id, n]));
  const subjects = graph.nodes
    .filter((n) => n.kind === 'identity')
    .filter((n) => rule.cameraIds.length === 0 || rule.cameraIds.includes(String(n.attributes.cameraId ?? '')))
    .sort((a, b) => a.id.localeCompare(b.id));

  const out: BehaviourCandidate[] = [];
  for (const subject of subjects) {
    const candidate = evaluateSubject(rule, graph, nodes, subject);
    if (candidate !== null) out.push(candidate);
  }
  return out;
}

function evaluateSubject(
  rule: BehaviourRule,
  graph: BehaviourGraphView,
  nodes: Map<string, GraphNode>,
  subject: GraphNode,
): BehaviourCandidate | null {
  /* ⛔ Every instant an operator reads is an offset from here. See `BehaviourGraphView.originSeconds`. */
  const origin = graph.originSeconds ?? 0;
  const since = (seconds: number): number => round(seconds - origin);
  const chain: BehaviourReasonLink[] = [];
  /*
   * ⚠️ **The cursor is what makes this a sequence**, and it advances to each matched fact's
   * **start**, never its end.
   *
   * ⛔ Advancing to the end was the first implementation and it was wrong in the most ordinary case
   * there is: a subject enters a zone at 5 s and stays until 20 s, then picks something up at 8 s.
   * The pick happens *inside* the visit, and a cursor at 20 s could never see it — so
   * "entered the aisle, then took a bottle" matched nothing at all. Sequencing means each fact
   * *began* at or after the last one began; it does not mean the facts cannot overlap, and almost
   * every interesting chain has them nested.
   *
   * `-Infinity` before the first step, because a chain has no start until it has one.
   */
  let cursor = -Infinity;
  let first: number | null = null;
  /* ⚠️ One edge cannot satisfy two steps. Without this, `carried` followed by `carried` would match
   * the same span twice and report a repetition that never happened. */
  const used = new Set<string>();

  for (const [index, step] of rule.steps.entries()) {
    const limit =
      first !== null && rule.withinSeconds !== undefined ? first + rule.withinSeconds : Infinity;
    const found = findStep(step, graph, nodes, subject, cursor, limit, used);

    if (step.absent) {
      /*
       * ⛔ An `absent` step matches when nothing was found — and records what it searched. The
       * evaluator cannot tell a meaningful absence from an empty graph, so it reports both numbers
       * and refuses to decide which the reader is looking at.
       */
      const matched = found === null;
      chain.push({
        index,
        step,
        matched,
        reason: matched
          ? `${phrase(step)} did not happen${window(cursor, limit, origin)} — ${found_considered(step, graph, nodes, subject, cursor, limit)} fact(s) of that kind were examined`
          : `${phrase(step)} did happen, at ${since(found.atSeconds)} s — the step required that it did not`,
        ...(matched ? {} : { atSeconds: since(found.atSeconds), footageAtSeconds: round(found.atSeconds) }),
        ...(matched || found.edgeId === undefined ? {} : { edgeId: found.edgeId }),
        evidence: matched ? {} : found.evidence,
        considered: found_considered(step, graph, nodes, subject, cursor, limit),
        ...(Number.isFinite(cursor) ? { searchedFromSeconds: since(cursor) } : {}),
        ...(Number.isFinite(limit) ? { searchedToSeconds: since(limit) } : {}),
      });
      if (!matched) return null;
      continue;
    }

    if (found === null) {
      chain.push({
        index,
        step,
        matched: false,
        reason: `${phrase(step)} was not found${window(cursor, limit, origin)}`,
        evidence: {},
        considered: found_considered(step, graph, nodes, subject, cursor, limit),
        ...(Number.isFinite(cursor) ? { searchedFromSeconds: since(cursor) } : {}),
        ...(Number.isFinite(limit) ? { searchedToSeconds: since(limit) } : {}),
      });
      return null;
    }

    chain.push({
      index,
      step,
      matched: true,
      reason: `${phrase(step)} — ${detailSince(found, origin)}`,
      atSeconds: since(found.atSeconds),
      footageAtSeconds: round(found.atSeconds),
      ...(found.endSeconds === undefined ? {} : { endSeconds: since(found.endSeconds) }),
      ...(found.seconds === undefined ? {} : { seconds: round(found.seconds) }),
      ...(found.edgeId === undefined ? {} : { edgeId: found.edgeId }),
      ...(found.nodeId === undefined ? {} : { nodeId: found.nodeId }),
      evidence: found.evidence,
    });
    if (first === null) first = found.atSeconds;
    if (found.edgeId !== undefined) used.add(found.edgeId);
    cursor = found.atSeconds;
  }

  const matched = chain.filter((link) => link.matched);
  if (matched.length !== rule.steps.length) return null;

  const instants = matched
    .flatMap((link) => [link.atSeconds, link.endSeconds])
    .filter((v): v is number => typeof v === 'number');

  return {
    ruleId: rule.id,
    ruleVersion: rule.version,
    ruleName: rule.name,
    label: rule.candidateLabel,
    severity: rule.severity,
    identityId: subject.id,
    cameraId: String(subject.attributes.cameraId ?? ''),
    ...(typeof subject.attributes.streamId === 'string'
      ? { streamId: subject.attributes.streamId }
      : {}),
    fromSeconds: instants.length > 0 ? Math.min(...instants) : 0,
    toSeconds: instants.length > 0 ? Math.max(...instants) : 0,
    footageFromSeconds: instants.length > 0 ? round(Math.min(...instants) + origin) : 0,
    footageToSeconds: instants.length > 0 ? round(Math.max(...instants) + origin) : 0,
    confidence: seekableShare(chain),
    chain,
    summary: `${rule.candidateLabel}: ${chain.map((link) => link.reason).join('; then ')}`,
  };
}

/**
 * ⛔ **Confidence is the share of links whose evidence points at a frame — a coverage measure.**
 *
 * A chain every link of which an investigator can open scores 1.0. It is emphatically **not** a
 * probability that the described intent occurred: this layer has no basis to claim one, and a number
 * that looked like a likelihood would be read as one by the first person to see it. ⚠️ An `absent`
 * link is counted as seekable — the absence *was* established over a stated window, and penalising a
 * rule for containing a negation would push authors to write worse rules.
 */
function seekableShare(chain: BehaviourReasonLink[]): number {
  if (chain.length === 0) return 0;
  const seekable = chain.filter(
    (link) => link.step.absent === true || link.evidence.frameIndex !== undefined,
  ).length;
  return Math.round((seekable / chain.length) * 1000) / 1000;
}

/** Candidate facts of a step's kind for this subject in the window — the denominator of an absence. */
function found_considered(
  step: BehaviourStep,
  graph: BehaviourGraphView,
  nodes: Map<string, GraphNode>,
  subject: GraphNode,
  after: number,
  limit: number,
): number {
  if (NODE_ATTRIBUTE_KINDS.has(step.kind)) {
    return subject.attributes[step.kind] === undefined ? 0 : 1;
  }
  return candidateEdges(step, graph, subject, after, limit).length;
}

function candidateEdges(
  step: BehaviourStep,
  graph: BehaviourGraphView,
  subject: GraphNode,
  after: number,
  limit: number,
): GraphEdge[] {
  return graph.edges.filter(
    (edge) =>
      edge.kind === step.kind &&
      involvesSubject(edge, step, subject) &&
      edge.atSeconds >= after &&
      edge.atSeconds <= limit,
  );
}

function involvesSubject(edge: GraphEdge, step: BehaviourStep, subject: GraphNode): boolean {
  if (SUBJECT_IS_TARGET.has(step.kind)) return edge.target === subject.id;
  if (SUBJECT_IS_SOURCE.has(step.kind)) return edge.source === subject.id;
  return edge.source === subject.id || edge.target === subject.id;
}

/**
 * The **earliest** fact satisfying a step at or after `after`, or `null`.
 *
 * ⚠️ Earliest, deliberately. A rule describes a story, and a story is told by the first thing that
 * happened next; matching the longest or the strongest would let a later, better fact reorder the
 * chain and make the same footage produce two different accounts.
 */
function findStep(
  step: BehaviourStep,
  graph: BehaviourGraphView,
  nodes: Map<string, GraphNode>,
  subject: GraphNode,
  after: number,
  limit: number,
  used: ReadonlySet<string> = new Set(),
): Match | null {
  if (NODE_ATTRIBUTE_KINDS.has(step.kind)) {
    const bucket = subject.attributes[step.kind] as { seconds?: number; episodes?: number } | undefined;
    if (bucket === undefined) return null;
    const seconds = Number(bucket.seconds ?? 0);
    if (step.minSeconds !== undefined && seconds < step.minSeconds) return null;
    /*
     * ⚠️ A node attribute is a fact about the whole run, so it has no instant of its own and does
     * **not** advance the cursor past anything. It is placed at the cursor so the chain stays
     * ordered without claiming a time it does not have.
     */
    return {
      atSeconds: Number.isFinite(after) ? after : 0,
      seconds,
      nodeId: subject.id,
      evidence: {},
      detail: `${seconds} s across ${Number(bucket.episodes ?? 0)} episode(s)`,
      considered: 1,
    };
  }

  const candidates = candidateEdges(step, graph, subject, after, limit).sort(
    (a, b) => a.atSeconds - b.atSeconds || a.id.localeCompare(b.id),
  );

  for (const edge of candidates) {
    if (used.has(edge.id)) continue;
    const other = nodes.get(edge.source === subject.id ? edge.target : edge.source);
    if (!matchesFilters(step, edge, other)) continue;
    const seconds = edge.seconds ?? (edge.endSeconds === undefined ? undefined : edge.endSeconds - edge.atSeconds);
    if (step.minSeconds !== undefined && (seconds ?? 0) < step.minSeconds) continue;
    return {
      atSeconds: edge.atSeconds,
      ...(edge.endSeconds === undefined ? {} : { endSeconds: edge.endSeconds }),
      ...(seconds === undefined ? {} : { seconds }),
      edgeId: edge.id,
      evidence: edge.evidence,
      detail: detail(edge, other, seconds),
      considered: candidates.length,
    };
  }
  return null;
}

function matchesFilters(step: BehaviourStep, edge: GraphEdge, other: GraphNode | undefined): boolean {
  if (step.zoneId !== undefined && String(edge.attributes.zoneId ?? '') !== step.zoneId) return false;
  if (step.lineId !== undefined && String(edge.attributes.lineId ?? '') !== step.lineId) return false;
  if (step.toSide !== undefined && String(edge.attributes.toSide ?? '') !== step.toSide) return false;
  if (step.objectLabel !== undefined && other?.label !== step.objectLabel) return false;
  if (step.otherLabel !== undefined && other?.label !== step.otherLabel) return false;
  return true;
}

function detail(edge: GraphEdge, other: GraphNode | undefined, seconds: number | undefined): string {
  /*
   * ⚠️ **The label alone for a place; the label AND the id for a subject.**
   *
   * A zone or line node's id is `zone:<zoneId>` / `line:<lineId>` — the same handle the step already
   * names in its filter — so printing both produced "crossed line zn-c82f… — Doorway line:zn-c82f…
   * at 16 s" on the deployment: the id three times in one sentence. An identity or object is the
   * opposite case: its label is a *class* ("person"), and an investigator needs the subject, so the
   * id is the informative half and must stay.
   */
  const what =
    other === undefined
      ? edge.target
      : other.kind === 'zone' || other.kind === 'line'
        ? other.label
        : `${other.label} ${other.id}`;
  const span = seconds === undefined ? '' : ` for ${round(seconds)} s`;
  /* ⚠️ The absolute instant, replaced by an offset in `detailSince` before a human sees it. */
  return `${what} at ${round(edge.atSeconds)} s${span}`;
}

/** The same sentence with the instant expressed as an offset into the run. */
function detailSince(found: Match, origin: number): string {
  return found.detail.replace(
    /at (-?\d+(?:\.\d+)?) s/,
    (_, raw: string) => `at ${round(Number(raw) - origin)} s`,
  );
}

/** The step in words. ⚠️ States the fact; the *rule's* label is the only place an intent may appear. */
function phrase(step: BehaviourStep): string {
  if (step.as !== undefined) return step.as;
  const parts: string[] = [step.kind];
  if (step.zoneId !== undefined) parts.push(`zone ${step.zoneId}`);
  if (step.lineId !== undefined) parts.push(`line ${step.lineId}`);
  if (step.toSide !== undefined) parts.push(`to the ${step.toSide}`);
  if (step.objectLabel !== undefined) parts.push(`a ${step.objectLabel}`);
  if (step.otherLabel !== undefined) parts.push(`a ${step.otherLabel}`);
  if (step.minSeconds !== undefined) parts.push(`for at least ${step.minSeconds} s`);
  return parts.join(' ');
}

function window(after: number, limit: number, origin: number): string {
  const since = (seconds: number): number => round(seconds - origin);
  if (!Number.isFinite(after) && !Number.isFinite(limit)) return '';
  if (!Number.isFinite(limit)) return ` after ${since(after)} s`;
  if (!Number.isFinite(after)) return ` before ${since(limit)} s`;
  return ` between ${since(after)} s and ${since(limit)} s`;
}

const round = (value: number): number => Math.round(value * 1000) / 1000;
