/**
 * Turn a run directory into something worth reading at 08:00.
 *
 *   node scripts/nightly/report.mjs --run reports/nightly/2026-08-06
 *
 * ### The one rule
 *
 * **Stages produce data; only this file interprets it.** A stage that decided for itself whether it
 * was a regression would be grading its own homework, and the thresholds would end up scattered
 * across eleven shell scripts. Everything here reads `journal.jsonl`, `status/` and `metrics/`.
 *
 * ### ⚠️ Absence is a verdict, not a gap
 *
 * A stage that was disabled, skipped, timed out or was never implemented is reported by name. The
 * failure this guards against is a summary that says GREEN because the only things that ran were the
 * things that could not fail — which is exactly how an unattended tool becomes a comfort blanket.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, lstatSync } from 'node:fs';
import { join, basename } from 'node:path';
import { read as historyRead } from './history.mjs';

const args = process.argv.slice(2);
const runFlag = args.indexOf('--run');
if (runFlag === -1) {
  console.error('usage: report.mjs --run <run-directory>');
  process.exit(2);
}
const RUN = args[runFlag + 1];
if (!existsSync(RUN)) {
  console.error(`no such run directory: ${RUN}`);
  process.exit(2);
}

const readJson = (path, fallback = null) => {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return fallback;
  }
};
const readText = (path) => {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return '';
  }
};

const run = readJson(join(RUN, 'run.json'), {});
const finished = readJson(join(RUN, 'finished.json'), {});
const journal = readText(join(RUN, 'journal.jsonl'))
  .split('\n')
  .filter(Boolean)
  .map((l) => {
    try {
      return JSON.parse(l);
    } catch {
      return null;
    }
  })
  .filter(Boolean);

/* ── stage outcomes ──────────────────────────────────────────────────────────────────────────── */

const statusDir = join(RUN, 'status');
const statuses = existsSync(statusDir)
  ? readdirSync(statusDir).filter((f) => !f.includes('.') && !f.startsWith('_'))
  : [];

// ⚠️ `kind === 'stage'` matters. The engine also journals run-level events (an abort) against the id
// of the stage that caused them, and that entry carries no duration — taking the last event of any
// kind made every aborting stage report its time as "—".
const stages = statuses.map((id) => {
  const status = readText(join(statusDir, id)).trim();
  const headline = readText(join(statusDir, `${id}.headline`)).trim();
  const events = journal.filter((e) => e.id === id && e.kind === 'stage');
  const last = events[events.length - 1] || {};
  return {
    id,
    status,
    headline: headline || last.detail || '',
    seconds: last.seconds ?? null,
    exit: last.exit ?? null,
    order: journal.findIndex((e) => e.id === id),
  };
});
stages.sort((a, b) => a.order - b.order);

const ICON = {
  passed: '✅',
  failed: '❌',
  timeout: '⏱️',
  skipped: '⏭️',
  disabled: '⚪',
  'not-implemented': '🚧',
  running: '⚠️',
};

const failed = stages.filter((s) => s.status === 'failed' || s.status === 'timeout');
const passed = stages.filter((s) => s.status === 'passed');
const skipped = stages.filter((s) => s.status === 'skipped');
const disabled = stages.filter((s) => s.status === 'disabled');
const missing = stages.filter((s) => s.status === 'not-implemented');
// ⚠️ `running` at report time means the stage never reported an outcome — the process died under it.
//
// Except this one. The report is generated BY a stage, so that stage is legitimately mid-flight
// while these lines execute. The first version reported itself as strangled and printed "the run was
// killed" on every healthy night — a self-inflicted false alarm, and the loudest line in the file.
const SELF = process.env.STAGE_ID || '';
const stranded = stages.filter((s) => s.status === 'running' && s.id !== SELF);

const treeState = readText(join(statusDir, '_tree')).trim();

/* ── verdict ─────────────────────────────────────────────────────────────────────────────────── */

let verdict = 'GREEN';
let verdictWhy = 'every stage that ran, passed';
if (failed.length > 0 || stranded.length > 0) {
  verdict = 'RED';
  verdictWhy = `${failed.length + stranded.length} stage(s) failed`;
} else if (treeState === 'dirty') {
  verdict = 'RED';
  verdictWhy = 'the working tree changed during the run';
} else if (passed.length === 0) {
  verdict = 'RED';
  verdictWhy = 'nothing actually ran';
} else if (skipped.length > 0) {
  verdict = 'AMBER';
  verdictWhy = `${skipped.length} stage(s) were skipped because something they depend on did not pass`;
}

/* ── metrics and trend ───────────────────────────────────────────────────────────────────────── */

const metricsDir = join(RUN, 'metrics');
const stability = readJson(join(metricsDir, 'stability.json'));
const benchmark = readJson(join(metricsDir, 'benchmark.json'));
const preflight = readJson(join(metricsDir, 'preflight.json'));

const num = (v, digits = 1) => (typeof v === 'number' && Number.isFinite(v) ? v.toFixed(digits) : '—');

/** The largest camera count whose frame loss is inside budget, with no earlier rung breaching it. */
function sustainable(rows, budget = 2) {
  let best = 0;
  for (const r of rows) {
    if (r.dropPercent <= budget && r.failed === 0) best = r.cameras;
    else break;
  }
  return best;
}

function summariseStability(data) {
  if (!data || !Array.isArray(data.samples) || data.samples.length === 0) return null;
  const s = data.samples;
  const pick = (k) => s.map((x) => x[k]).filter((n) => typeof n === 'number' && n > 0);
  const half = Math.floor(s.length / 2);
  const mean = (xs) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);
  const memFirst = mean(s.slice(0, half).map((x) => x.runtimeMem).filter(Boolean));
  const memSecond = mean(s.slice(half).map((x) => x.runtimeMem).filter(Boolean));
  const perFrame = pick('perFrame');
  return {
    minutes: s.length,
    cameras: data.cameras,
    frames: s.reduce((a, x) => a + (x.delivered || 0), 0),
    dropped: s.reduce((a, x) => a + (x.dropped || 0), 0),
    memoryLow: Math.min(...pick('runtimeMem')),
    memoryHigh: Math.max(...pick('runtimeMem')),
    memoryDriftPercent: memFirst > 0 ? ((memSecond - memFirst) / memFirst) * 100 : 0,
    p95Low: Math.min(...pick('runtimeP95')),
    p95High: Math.max(...pick('runtimeP95')),
    perFrameLow: perFrame.length ? Math.min(...perFrame) : 0,
    perFrameHigh: perFrame.length ? Math.max(...perFrame) : 0,
    queuePeak: Math.max(0, ...s.map((x) => x.queueDepth || 0)),
  };
}

function summariseBenchmark(data) {
  if (!data || !Array.isArray(data.rows) || data.rows.length === 0) return null;
  const rows = data.rows;
  const cams = sustainable(rows);
  const at = rows.find((r) => r.cameras === cams) || rows[0];
  const top = rows[rows.length - 1];
  return {
    rows,
    sustainable: cams,
    p95AtSustainable: at?.latencyP95Ms ?? null,
    cpuAtSustainable: at?.runtimeCpu ?? null,
    memAtSustainable: at?.runtimeMem ?? null,
    dropAtSustainable: at?.dropPercent ?? null,
    topCameras: top?.cameras ?? null,
    topDrop: top?.dropPercent ?? null,
    warmup: data.warmup ?? null,
    reproducibility: data.reproducibility ?? null,
  };
}

/**
 * The tracking ladder and the authored-scenario accuracy run.
 *
 * ⚠️ **Two files, never merged, and the report keeps them apart on purpose.** The ladder measures
 * identity under LOAD against live streams and is as blind to an identity switch as production is.
 * `tracking-truth.json` measures whether the tracker was RIGHT, and can only do so because the
 * trajectories were authored first. Presenting one number sourced from either would be exactly the
 * confusion ADR-0039 exists to prevent.
 */
function summariseTracking(data) {
  if (!data || !Array.isArray(data.rows) || data.rows.length === 0) return null;
  const rows = data.rows;
  const clean = rows.filter((r) => r.identityOverhead === 0).map((r) => r.cameras);
  const top = rows[rows.length - 1];
  return {
    rows,
    identityIntactTo: clean.length ? Math.max(...clean) : 0,
    topCameras: top?.cameras ?? null,
    topOverhead: top?.identityOverhead ?? null,
    topDrop: top?.dropPercent ?? null,
    trackingMsMax: Math.max(...rows.map((r) => r.trackingMsAvg ?? 0)),
    occlusions: rows.reduce((a, r) => a + (r.occlusionsSurvived ?? 0), 0),
    crossings: rows.reduce((a, r) => a + (r.crossings ?? 0), 0),
    sizingPolicy: data.sizingPolicy ?? null,
  };
}

const stab = summariseStability(stability);
const bench = summariseBenchmark(benchmark);
const track = summariseTracking(readJson(join(metricsDir, 'tracking-benchmark.json')));
const truth = readJson(join(metricsDir, 'tracking-truth.json'));

/**
 * The previous run worth comparing against.
 *
 * ⚠️ Only runs that produced the metric are candidates. Comparing today's benchmark against a night
 * where the benchmark stage was disabled would invent a trend out of an absence.
 */
function previousRun(metricFile) {
  const root = join(RUN, '..');
  const mine = basename(RUN);
  const candidates = readdirSync(root)
    .filter((d) => {
      if (d === mine) return false;
      // ⚠️ Real directories only. `latest` is a symlink to a run — usually THIS one — and excluding
      // it by name is not enough because it has a different name. Without this the trend compared
      // the run against itself and reported a confident "+0.0 %" on every line, which looks exactly
      // like a stable platform and is in fact no comparison at all.
      try {
        if (!lstatSync(join(root, d)).isDirectory()) return false;
      } catch {
        return false;
      }
      return existsSync(join(root, d, 'metrics', metricFile));
    })
    .sort();
  const prev = candidates[candidates.length - 1];
  return prev ? { id: prev, data: readJson(join(root, prev, 'metrics', metricFile)) } : null;
}

const cfg = {
  p95: Number(process.env.REGRESS_P95_PERCENT ?? 20),
  memory: Number(process.env.REGRESS_MEMORY_PERCENT ?? 15),
  drop: Number(process.env.REGRESS_DROP_POINTS ?? 3),
};

const trends = [];
const regressions = [];

/** The persistent ledger, or an empty list if it has not been written yet. Never fatal. */
function history(family, limit = 0) {
  try {
    return historyRead(family, limit);
  } catch {
    return [];
  }
}

const prevBench = previousRun('benchmark.json');
if (bench && prevBench) {
  const before = summariseBenchmark(prevBench.data);
  if (before) {
    const delta = (a, b) => (b === 0 || b == null || a == null ? null : ((a - b) / b) * 100);
    const p95Delta = delta(bench.p95AtSustainable, before.p95AtSustainable);
    const memDelta = delta(bench.memAtSustainable, before.memAtSustainable);
    const dropDelta =
      bench.dropAtSustainable != null && before.dropAtSustainable != null
        ? bench.dropAtSustainable - before.dropAtSustainable
        : null;

    trends.push(
      `**Sustainable cameras** ${before.sustainable} → **${bench.sustainable}** (vs \`${prevBench.id}\`)`,
      `**p95 at that rung** ${num(before.p95AtSustainable)} ms → **${num(bench.p95AtSustainable)} ms**` +
        (p95Delta == null ? '' : ` (${p95Delta >= 0 ? '+' : ''}${p95Delta.toFixed(1)} %)`),
      `**Runtime memory** ${num(before.memAtSustainable, 0)} MB → **${num(bench.memAtSustainable, 0)} MB**` +
        (memDelta == null ? '' : ` (${memDelta >= 0 ? '+' : ''}${memDelta.toFixed(1)} %)`),
      `**Frame loss** ${num(before.dropAtSustainable, 2)} % → **${num(bench.dropAtSustainable, 2)} %**`,
    );

    if (bench.sustainable < before.sustainable)
      regressions.push(
        `**Capacity fell**: ${before.sustainable} → ${bench.sustainable} cameras inside the loss budget.`,
      );
    if (p95Delta != null && p95Delta > cfg.p95)
      regressions.push(`**p95 rose ${p95Delta.toFixed(1)} %** at the sustainable rung (threshold ${cfg.p95} %).`);
    if (memDelta != null && memDelta > cfg.memory)
      regressions.push(`**Runtime memory rose ${memDelta.toFixed(1)} %** (threshold ${cfg.memory} %).`);
    if (dropDelta != null && dropDelta > cfg.drop)
      regressions.push(
        `**Frame loss rose ${dropDelta.toFixed(2)} points** at the sustainable rung (threshold ${cfg.drop}).`,
      );
  }
} else if (bench) {
  trends.push('_First run carrying a benchmark — nothing to compare against yet._');
}

/*
 * ### ⚠️ The long horizon comes from the LEDGER, not from the run directories
 *
 * `previousRun()` above compares against the last night that produced the metric, and that is the
 * right comparison for "did something break yesterday?". It cannot answer "is this creeping?",
 * because run directories are pruned after `KEEP_RUNS` days — so a walk over them has a one-month
 * memory however long the platform has been running. The ledger is append-only and outside the run
 * root, so it does not.
 */
if (track) {
  const ledger = history('tracking', 10);
  // ⚠️ Excluding THIS run: it is appended after the report is generated, but a re-run of the report
  // over an existing directory would otherwise compare the run against itself.
  const past = ledger.filter((row) => row.runId !== basename(RUN));
  if (past.length >= 2) {
    const first = past[0];
    const intact = past.map((r) => r.identityIntactToCameras ?? 0);
    trends.push(
      `**Identity intact to** ${first.identityIntactToCameras} → **${track.identityIntactTo}** camera(s) ` +
        `over ${past.length} recorded run(s) (range ${Math.min(...intact)}–${Math.max(...intact)})`,
    );
    const costs = past.map((r) => r.trackingMsMax ?? 0).filter((n) => n > 0);
    if (costs.length > 0)
      trends.push(
        `**Tracking cost** ${Math.min(...costs).toFixed(3)}–${Math.max(...costs).toFixed(3)} ms/frame historically, ` +
          `**${track.trackingMsMax.toFixed(3)} ms** tonight`,
      );
  }
}

{
  /*
   * ⚠️ The sizing rule, checked rather than restated. "No published recommendation until three
   * independent runs agree" is only a policy if something counts the runs — otherwise it is a
   * sentence in a document that a confident summary quietly contradicts.
   */
  const ledger = history('benchmark', 6).filter((row) => row.runId !== basename(RUN));
  const recent = ledger.slice(-3).map((r) => r.sustainableCameras);
  if (bench) {
    const agree = recent.length === 3 && new Set(recent).size === 1;
    trends.push(
      agree
        ? `**Sizing:** the last three recorded runs agree at ${recent[0]} camera(s) — a recommendation may be published.`
        : `**Sizing: PROVISIONAL.** ${
            recent.length < 3
              ? `only ${recent.length} recorded run(s) so far`
              : `the last three runs measured ${recent.join(', ')}`
          } — no recommendation is published until three independent runs agree.`,
    );
  }
}

const prevStab = previousRun('stability.json');
if (stab && prevStab) {
  const before = summariseStability(prevStab.data);
  if (before) {
    trends.push(
      `**Stability memory band** ${num(before.memoryLow, 0)}–${num(before.memoryHigh, 0)} MB → ` +
        `**${num(stab.memoryLow, 0)}–${num(stab.memoryHigh, 0)} MB**`,
    );
    if (stab.memoryDriftPercent > cfg.memory)
      regressions.push(
        `**Memory drifted ${stab.memoryDriftPercent.toFixed(1)} %** between the halves of the stability run ` +
          `(threshold ${cfg.memory} %) — this is the shape a leak has.`,
      );
  }
}

// ⚠️ Detection consistency is the AI-side check and it is not a trend, it is a floor. Two people in
// the scene means 2.00 per frame; anything else means the runtime stopped seeing a person, and no
// operational metric above would notice.
if (stab && (stab.perFrameLow < 1.95 || stab.perFrameHigh > 2.05)) {
  regressions.push(
    `**Detection consistency broke**: ${stab.perFrameLow.toFixed(2)}–${stab.perFrameHigh.toFixed(2)} per frame, ` +
      'expected 2.00. The runtime stopped seeing a person it should see.',
  );
}

/* ── actions ─────────────────────────────────────────────────────────────────────────────────── */

const actions = [];
if (stranded.length)
  actions.push(
    `**Find out why the run died.** ${stranded.map((s) => `\`${s.id}\``).join(', ')} never reported an ` +
      'outcome, which means the process was killed under it — sleep, a closed terminal, or an OOM.',
  );
if (treeState === 'dirty')
  actions.push('**Check `logs/tree-drift.log` before anything else** — a stage left the working tree modified.');
for (const s of failed) actions.push(`Read \`logs/${s.id}.log\` — ${s.headline || 'failed'}.`);
if (skipped.length)
  actions.push(
    `${skipped.length} stage(s) never ran because a dependency failed. Fix the dependency and ` +
      `\`./scripts/nightly.sh --resume --run-id ${run.runId}\` picks up where this left off.`,
  );
for (const r of regressions) actions.push(r);
if (missing.length)
  actions.push(
    `${missing.length} stage(s) are placeholders for work not yet done: ` +
      `${missing.map((s) => `\`${s.id}\``).join(', ')}.`,
  );
if (actions.length === 0) actions.push('Nothing. Carry on building.');

/* ── summary.md ──────────────────────────────────────────────────────────────────────────────── */

const dur = (s) => {
  if (s == null) return '—';
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  return h > 0 ? `${h}h ${m}m` : m > 0 ? `${m}m ${s % 60}s` : `${s}s`;
};

const banner = verdict === 'GREEN' ? '## ✅ GREEN' : verdict === 'AMBER' ? '## 🟠 AMBER' : '## ❌ RED';

let summary = `# Nightly verification — ${run.runId ?? basename(RUN)}

${banner}

**${verdictWhy}.**

| | |
| --- | --- |
| **Profile** | \`${run.profile ?? '?'}\` |
| **Commit** | \`${run.commit ?? '?'}\` |
| **Started** | ${run.startedAt ?? '?'} |
| **Duration** | ${dur(finished.seconds)} |
| **Working tree** | ${treeState === 'clean' ? 'unchanged by this run ✅' : treeState === 'dirty' ? '**CHANGED — see logs/tree-drift.log** ❌' : '—'} |

## Stages

| | Stage | Outcome | Took | Headline |
| :-: | --- | --- | ---: | --- |
${stages
  .map(
    (s) =>
      `| ${s.id === SELF && s.status === 'running' ? '✍️' : (ICON[s.status] ?? '•')} | \`${s.id}\` | ${s.id === SELF && s.status === 'running' ? 'generating this report' : s.status} | ${dur(s.seconds)} | ${s.headline || '—'} |`,
  )
  .join('\n')}

${stranded.length ? `> ⚠️ **${stranded.map((s) => s.id).join(', ')} never finished.** The run was killed while they were executing — a sleeping machine is the usual cause. \`KEEP_AWAKE=true\` wraps the run in \`caffeinate\`.\n` : ''}
${missing.length ? `> 🚧 **Not implemented:** ${missing.map((s) => `\`${s.id}\``).join(', ')}. These are placeholders for milestones that have not happened. They are reported, never counted as passes.\n` : ''}
## Recommended actions

${actions.map((a) => `1. ${a}`).join('\n')}
`;

if (stab) {
  summary += `
## Resource trend — stability run

${stab.minutes} minutes · ${stab.cameras} cameras · ${stab.frames} frames analysed

| | |
| --- | --- |
| **Detection consistency** | ${stab.perFrameLow.toFixed(2)}–${stab.perFrameHigh.toFixed(2)} per frame ${stab.perFrameLow >= 1.95 && stab.perFrameHigh <= 2.05 ? '✅' : '❌'} |
| **Memory** | ${num(stab.memoryLow, 0)}–${num(stab.memoryHigh, 0)} MB · drift between halves ${stab.memoryDriftPercent >= 0 ? '+' : ''}${stab.memoryDriftPercent.toFixed(1)} % |
| **p95 inference** | ${num(stab.p95Low, 0)}–${num(stab.p95High, 0)} ms |
| **Queue peak** | ${stab.queuePeak} |
| **Dropped** | ${stab.dropped} |
`;
}

if (bench) {
  summary += `
## Performance — capacity

**Sustainable: ${bench.sustainable} camera(s)** at the configured frame rate — p95 ${num(bench.p95AtSustainable)} ms, ${num(bench.cpuAtSustainable, 0)} % CPU, ${num(bench.memAtSustainable, 0)} MB.
At ${bench.topCameras} cameras the platform loses ${num(bench.topDrop)} % of offered frames.

See [benchmark.md](benchmark.md) for the full ladder.
`;
}

if (track) {
  summary += `
## Tracking — identity under load

**Identity intact to ${track.identityIntactTo} camera(s)** — one walking person per camera produced
exactly one identity per camera up to that rung. At ${track.topCameras} cameras the engine produced
${track.topOverhead} extra identity(ies) and lost ${num(track.topDrop)} % of offered frames.
Tracking costs at most ${track.trackingMsMax.toFixed(3)} ms per frame.

${track.occlusions} occlusion(s) absorbed · ${track.crossings} crossing(s) observed.

> ⚠️ **Extra identities here are FRAGMENTATION, not swapping.** Fewer analysed frames per camera
> means a larger gap between observations, and past the engine's tolerance a new identity is the
> correct answer. Nothing in this ladder can tell fragmentation from a swap — that needs ground
> truth, and it is measured separately below.
>
> ⚠️ **Do not read this table as a sizing revision.** The ladder streams a synthetic clip that is far
> cheaper to encode and decode than a real scene${
    track.sizingPolicy
      ? `. Supported remains **${track.sizingPolicy.supported} camera(s)**, ${track.sizingPolicy.provisional} provisional — ${track.sizingPolicy.rule}`
      : ''
  }.
`;
}

if (truth?.metrics) {
  const label = {
    identityStability: 'Identity stability',
    reidentificationSuccess: 'Re-identification success',
    occlusionRecovery: 'Occlusion recovery',
    crossingCorrectness: 'Crossing correctness',
    identitySwitches: 'Identity switches',
    terminationCorrectness: 'Termination correctness',
    falseRecoveries: 'False recoveries',
  };
  const rows = Object.entries(truth.metrics).map(([key, value]) => {
    const basis = truth.basis?.[key];
    return `| **${label[key] ?? key}** | ${
      value === null ? '_not measured_' : `\`${value}\``
    } | ${basis?.detail ?? (value === null ? 'scenario did not run' : '—')} |`;
  });
  summary += `
## Tracking — accuracy against authored ground truth

Scenarios run: ${(truth.scenariosRun ?? []).map((x) => `\`${x}\``).join(', ') || '_none_'}

| Metric | Value | Basis |
| --- | --- | --- |
${rows.join('\n')}

> ⚠️ **This is the only place on the platform these numbers exist.** \`/tracking\` reports identity
> switches, re-identification success and false recoveries as \`null\`, because a live camera cannot
> say which real object an identity belonged to (ADR-0039). They are answerable here because the
> trajectories were written down before the run.
>
> ⚠️ **${truth.caveat ?? 'Measured against authored clips, not real CCTV.'}**
`;
}

if (trends.length) {
  summary += `
## Trend

${trends.map((t) => `- ${t}`).join('\n')}
`;
}

summary += `
---

_Generated by \`scripts/nightly/report.mjs\`. Raw logs in [\`logs/\`](logs/), raw samples in [\`metrics/\`](metrics/)._
`;

writeFileSync(join(RUN, 'summary.md'), summary);

/* ── verification.md ─────────────────────────────────────────────────────────────────────────── */

let verification = `# Verification detail — ${run.runId ?? basename(RUN)}

What each stage asserted, and what it reported. The summary is the verdict; this is the evidence.

`;
for (const s of stages) {
  const log = readText(join(RUN, 'logs', `${s.id}.log`));
  const checks = log.split('\n').filter((l) => /^\s{2}[✓✗⚠️·]/.test(l));
  verification += `## ${ICON[s.status] ?? '•'} ${s.id} — ${s.status}\n\n`;
  if (s.headline) verification += `**${s.headline}**\n\n`;
  if (checks.length) {
    verification += '```\n' + checks.slice(0, 60).join('\n') + '\n```\n\n';
    if (checks.length > 60) verification += `_…${checks.length - 60} more lines in \`logs/${s.id}.log\`._\n\n`;
  } else if (s.status === 'not-implemented') {
    verification += '_No script exists for this stage. It is a placeholder for work not yet done._\n\n';
  } else if (s.status === 'disabled') {
    verification += '_Switched off in configuration._\n\n';
  } else if (s.status === 'skipped') {
    verification += '_Never ran — something it depends on did not pass._\n\n';
  } else {
    verification += `_No check lines captured; see \`logs/${s.id}.log\`._\n\n`;
  }
}
writeFileSync(join(RUN, 'verification.md'), verification);

/* ── benchmark.md ────────────────────────────────────────────────────────────────────────────── */

if (bench) {
  const w = bench.warmup ?? {};
  const rep = bench.reproducibility ?? {};
  const bm = `# AI runtime benchmark — measured ${run.runId ?? basename(RUN)}

> Generated from a live run by \`scripts/nightly/report.mjs\`.
>
> ⚠️ **This is a run record, not the platform's reference page.** The committed reference lives at
> [\`docs/project/AI_RUNTIME_BENCHMARK.md\`](../../../docs/project/AI_RUNTIME_BENCHMARK.md) and is
> updated only by a person: \`scripts/benchmark.sh --promote ${run.runId ?? ''}\`. A permanent
> reference a machine can rewrite at 03:00 is not a reference.

**Commit** \`${run.commit ?? '?'}\` · **execution provider** ${preflight?.executionProvider ?? '—'}

## Capacity ladder

| Cameras | Offered fps | Analysed fps | Detections/s | Avg | p95 | Dropped | Drop % | Queue peak | Runtime CPU / RAM |
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | :-: | ---: |
${bench.rows
  .map(
    (r) =>
      `| **${r.cameras}** | ${num(r.offeredFps)} | **${num(r.fps)}** | ${num(r.detectionsPerSecond)} | ${num(r.latencyAvgMs)} ms | ${num(r.latencyP95Ms)} ms | ${r.dropped} | ${num(r.dropPercent, 1)} % | ${r.queuePeak ?? '—'}/${r.runtimeQueuePeak ?? '—'} | ${num(r.runtimeCpu, 0)} % / ${num(r.runtimeMem, 0)} MB |`,
  )
  .join('\n')}

**Sustainable: ${bench.sustainable} camera(s)** — the largest rung inside a 2 % frame-loss budget with
no earlier rung breaching it.

## Warm-up

| | Unwarmed | Warmed |
| --- | --- | --- |
| First inference | ${num(w.firstColdMs)} ms | ${num(w.firstWarmMs)} ms |
| Steady state | ${num(w.warmedColdMs)} ms | ${num(w.warmedWarmMs)} ms |
| Warm-up itself | — | ${num(w.warmupMs, 0)} ms |

## Reproducibility

${rep.runs ?? '—'} runs of one frame · confidence variance ${rep.variance === 0 ? '**exactly zero**' : rep.variance ?? '—'} · distinct values per detection: ${(rep.distinctConfidences ?? []).join(', ') || '—'}
`;
  writeFileSync(join(RUN, 'benchmark.md'), bm);
}

/* ── INDEX.md — every run, one table ─────────────────────────────────────────────────────────── */
/*
 * ⚠️ Rebuilt from the runs on disk each time rather than appended to. An index that is appended to
 * drifts the moment `cleanup.sh` prunes an old run, and then it lists evidence that no longer
 * exists — which is worse than no index, because you go looking for it.
 */
{
  const root = join(RUN, '..');
  const rows = readdirSync(root)
    // ⚠️ `lstatSync`, so `latest` is excluded. It is a symlink to a run, and `existsSync` follows it
    // — the index listed every night twice, once under its date and once as "latest".
    .filter((d) => {
      try {
        return lstatSync(join(root, d)).isDirectory() && existsSync(join(root, d, 'run.json'));
      } catch {
        return false;
      }
    })
    .sort()
    .reverse()
    .map((d) => {
      const meta = readJson(join(root, d, 'run.json'), {});
      const fin = readJson(join(root, d, 'finished.json'), {});
      const sm = readText(join(root, d, 'summary.md'));
      const v = /^## (✅ GREEN|🟠 AMBER|❌ RED)/m.exec(sm);
      const why = /^\*\*(.+?)\.\*\*$/m.exec(sm);
      return { id: d, meta, fin, verdict: v ? v[1] : '—', why: why ? why[1] : '' };
    });

  const index = `# Nightly verification — every run

**Latest:** [\`latest/summary.md\`](latest/summary.md) — a stable path that always points at the
newest run, so it never needs a date.

| Run | Verdict | Profile | Commit | Duration | What it says |
| --- | --- | --- | --- | ---: | --- |
${rows
  .map(
    (r) =>
      `| [\`${r.id}\`](${r.id}/summary.md) | ${r.verdict} | \`${r.meta.profile ?? '?'}\` | \`${r.meta.commit ?? '?'}\` | ${dur(r.fin.seconds)} | ${r.why || '—'} |`,
  )
  .join('\n')}

---

_Rebuilt by \`scripts/nightly/report.mjs\` on every run. Old runs are pruned by
\`scripts/cleanup.sh --prune\` (KEEP_RUNS days), and this table is regenerated from what survives._
`;
  writeFileSync(join(root, 'INDEX.md'), index);
}

/* ── console ─────────────────────────────────────────────────────────────────────────────────── */

console.log('');
console.log(`  ${verdict} — ${verdictWhy}`);
console.log(`  ${passed.length} passed · ${failed.length} failed · ${skipped.length} skipped · ${disabled.length} disabled · ${missing.length} not implemented`);
console.log(`  summary → ${join(RUN, 'summary.md')}`);
console.log('');

process.exit(0);
