/**
 * The investigation playback session (P-5.4, Architect rec 1) — the requested field list, held
 * where the requirement's own last line says it belongs.
 *
 * > "Session restoration must restore only UI state, never business state."
 *
 * ### ⚠️ That line resolves the tension in the rest of the list
 *
 * `sessionId`, `resumeToken` and `expiresAt` read like a server-side resource with a lifecycle, and
 * `PlaybackSession`'s frozen decision 1 refuses one: the segments and signed URLs are recomputed
 * from records that already exist, so a stored session goes stale while claiming to be current.
 * Both things are satisfied at once by noticing what each field is *for*:
 *
 * - **`sessionId`** is a correlation id, generated by the client. It ties an operator's scrubbing to
 *   the access-audit entries it produced. It grants nothing.
 * - **`resumeToken`** is an **opaque encoding of {@link PlaybackRestore}** — a query and a position.
 *   ⚠️ It is explicitly **not a bearer credential**: restoring re-runs the query under the
 *   restorer's own identity and permissions. A token that carried authority would let a link
 *   pasted into a chat outlive the revocation of the person who made it.
 * - **`expiresAt`** is the signed-URL horizon, derived from the earliest segment expiry — the
 *   moment the descriptor stops working, not a server-side timeout.
 *
 * ### ⚠️ `activeBookmarks` and `activeAnnotations` are id lists, never records
 *
 * A bookmark or an annotation is investigation data. Persisting the *records* into the operator's
 * browser would put business state in `localStorage`, where it survives the incident being closed,
 * the annotation being revised, and the operator's access being withdrawn — and it would be read
 * back and rendered as current. Ids restore a *selection*; the records are always re-fetched under
 * a live permission check. Same rule as `WorkspaceUiState.bookmarkIds` (§65).
 *
 * ⚠️ **Frozen with no producer.** Nothing opens, stores or restores one of these.
 */
import { z } from 'zod';
import { IsoDateTime, TenantId, Uuid } from '../common/primitives.js';
import { PlaybackRestore, PlaybackSource } from './playback.js';

/**
 * What the player is doing.
 *
 * ⚠️ `unavailable` is here for the same reason it is the fourth render state (DESIGN_SYSTEM §11):
 * a source that cannot be played is not "paused", and an operator who reads it as paused will press
 * play and conclude the product is broken.
 */
export const PlaybackState = z.enum([
  'idle',
  'playing',
  'paused',
  'stopped',
  'buffering',
  'ended',
  'unavailable',
]);
export type PlaybackState = z.infer<typeof PlaybackState>;

/**
 * ⚠️ **What the player is actually managing to show** — "show dropped frames, buffering and stream
 * quality honestly."
 *
 * A player that silently drops frames while the scrubber advances smoothly tells an investigator
 * they watched a corridor for thirty seconds when they saw eight frames of it. That is the same
 * class of failure as a compressed recording gap: the timeline looks continuous, so the absence
 * never becomes a question.
 *
 * ⚠️ Every field is **optional, and absent means not measured** — never zero. A `droppedFrames: 0`
 * from a player that does not count frames is a stronger claim than "we didn't look", and it is the
 * claim that would be quoted.
 */
export const PlaybackQuality = z.object({
  /** Frames the decoder discarded. Absent ⇒ not counted by this player or this source. */
  droppedFrames: z.number().int().min(0).optional(),
  /** Frames actually presented, so `dropped` has a denominator worth reading. */
  renderedFrames: z.number().int().min(0).optional(),
  /** Seconds spent stalled waiting for data, cumulative. */
  bufferingSeconds: z.number().nonnegative().optional(),
  /** Number of stalls — one long stall and forty short ones feel completely different. */
  stallCount: z.number().int().min(0).optional(),
  /** The rendition in use, when the source offers more than one. */
  renditionLabel: z.string().min(1).max(80).optional(),
  observedAt: IsoDateTime.optional(),
});
export type PlaybackQuality = z.infer<typeof PlaybackQuality>;

/**
 * Is the playback good enough to reason from?
 *
 * ⚠️ Returns `undefined` when nothing was measured, rather than `true`. "No evidence of a problem"
 * and "evidence of no problem" are different, and only the second one should ever quiet a warning.
 */
export function playbackIsClean(quality: PlaybackQuality): boolean | undefined {
  if (quality.droppedFrames === undefined && quality.stallCount === undefined) return undefined;
  return (quality.droppedFrames ?? 0) === 0 && (quality.stallCount ?? 0) === 0;
}

/**
 * An opaque resume token.
 *
 * ⚠️ Constrained in shape but **never parsed for meaning by a consumer** — it encodes a
 * {@link PlaybackRestore} and nothing else. Typed as a string so a future encoding change is not a
 * breaking change, and length-bounded so it cannot become a place to smuggle state.
 */
export const ResumeToken = z.string().min(1).max(2048);
export type ResumeToken = z.infer<typeof ResumeToken>;

/**
 * The operator's playback session — **UI state, client-owned**.
 *
 * Everything here answers "where was I", and nothing here is a source of truth about the
 * investigation. It is safe to lose: losing it costs an operator their scroll position, not a
 * record.
 */
export const InvestigationPlaybackSession = z.object({
  /** ⚠️ Client-generated. A correlation id for the audit trail, not a handle to a resource. */
  sessionId: Uuid,
  tenantId: TenantId,
  incidentId: z.string().min(1).optional(),
  /** ⚠️ Encodes the restore descriptor. Carries no authority — see the module note. */
  resumeToken: ResumeToken.optional(),
  /** Whose session this is. Restoring under a different principal re-authorises from scratch. */
  openedBy: z.string().min(1),
  openedAt: IsoDateTime,
  /**
   * ⚠️ When the resolved descriptor's URLs stop working, derived from the earliest segment expiry.
   * Absent ⇒ nothing has been resolved yet, never "no expiry".
   */
  expiresAt: IsoDateTime.optional(),
  playbackState: PlaybackState.default('idle'),
  playbackRate: z.number().positive().default(1),
  /** Which evidence item the viewer has open. */
  activeEvidenceId: z.string().min(1).optional(),
  /** Which camera is active on a wall — the one keyboard commands act on. */
  selectedCameraId: z.string().min(1).optional(),
  /** Which timeline track is in focus. */
  selectedTimelineId: z.string().min(1).optional(),
  /** The wall's sources. Bounded by the sync budget; see `PLAYBACK_SYNC_MAX_SOURCES`. */
  synchronizedSources: z.array(PlaybackSource).max(9).default([]),
  /** ⚠️ Ids only. See the module note. */
  activeBookmarkIds: z.array(z.string().min(1)).max(200).default([]),
  /** ⚠️ Ids only. See the module note. */
  activeAnnotationIds: z.array(z.string().min(1)).max(200).default([]),
  /** The position to come back to, when one has been saved. */
  restore: PlaybackRestore.optional(),
  /** ⚠️ What the player actually managed to show. Absent ⇒ not measured. */
  quality: PlaybackQuality.optional(),
});
export type InvestigationPlaybackSession = z.infer<typeof InvestigationPlaybackSession>;

/**
 * Fields that must never appear on a persisted session, exported as data so a test asserts it.
 *
 * ⚠️ Each of these is **business state**: a record whose truth lives on the server and whose stale
 * copy in a browser would be rendered as current. The id-carrying equivalents are on the session
 * instead.
 */
export const SESSION_FORBIDDEN_KEYS = [
  'bookmarks',
  'annotations',
  'incident',
  'evidence',
  'segments',
  'markers',
  'permissions',
] as const;

/**
 * Is a session still usable, or must it be re-derived?
 *
 * ⚠️ Absent `expiresAt` returns `false` — nothing has been resolved, so there is nothing to reuse.
 * Returning `true` would let a caller skip the resolution it has not yet made.
 */
export function sessionIsLive(session: InvestigationPlaybackSession, now: Date): boolean {
  if (session.expiresAt === undefined) return false;
  return Date.parse(session.expiresAt) > now.getTime();
}
